### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by Nicoretti** [silentbicycle/lunatest#20]
please add licensing information, so potential users can check if they
can use it in their project.

**Comment by silentbicycle** [comment]
There's already [a license](https://github.com/silentbicycle/lunatest/blob/master/lunatest.lua#L5) in the source file. Am I missing something?

**Comment by Nicoretti** [comment]
Thats true for this file but, what about the overall project? Due to the fact that the most other files are missing the license header would be nice to have at least a license file/statement for the project.
For example at work I would be only allowed to use the single file due the fact that everything else is unclear ...

appreciating you taking the time to discuss this with me.

greez
Nico

**Comment by silentbicycle** [comment]
I'll put something in the readme noting that the entire project is distributed under the same license.

**Comment by silentbicycle** [comment]
Closed by 94d3b3773af1c935e86feac5e88faf107b803bcb.
